[env]
_.path = [ "./node_modules/.bin" ]

RUSTUP_TOOLCHAIN = "1.96.1-x86_64-pc-windows-gnu"

[tools]
# Environments
bun = "1.3.14"
aube = "1.26.0"
rust = "1.96.1"
# Linters & Formatters
hk = "1.50.0"
stylua = "2.5.2"
pkl = "0.31.1"
"cargo:https://github.com/nushell/nufmt" = "branch:main"
shfmt = "latest"

[deps.bun-aube]
description = "Automatically install dependencies via aube & bun's lockfile."
sources = [
  "package.json",
  "bun.lock"
]
outputs = [ "node_modules/" ]
# Because aube's output lockfile has bugs,
# we use `bun install --lockfile-only` to generate a lockfile
run = "bun install --lockfile-only && aube install"
auto = true

[tasks.check]
run = "hk check --all"

[tasks.fix]
run = "hk fix --all"
