[env]
_.path = [ "./node_modules/.bin" ]

[tools]
# Environments
bun = "latest"
node = "24"
aube = "latest"
rust = "stable-gnu"
go = "latest"
# Linters & Formatters
hk = "latest"
stylua = "latest"
pkl = "latest"
"cargo:https://github.com/nushell/nufmt" = "branch:main"
shfmt = "latest"
"go:github.com/gohugoio/gotmplfmt" = "latest"

[deps.bun-aube]
description = "Automatically install dependencies via aube & bun's lockfile."
sources = [
  "package.json",
  "bun.lock"
]
outputs = [ "node_modules/" ]
# Because aube's output lockfile has bugs,
# we use `bun install --lockfile-only` to generate a lockfile
run = "bun install --lockfile-only && aube install"
auto = true

[tasks.check]
run = "hk check --all"

[tasks.fix]
run = "hk fix --all"
