# Clash Verge DNS Config

dns:
  enable: true
  listen: :53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  prefer-h3: false
  respect-rules: false
  use-hosts: false
  use-system-hosts: false
  fake-ip-filter:
    - 'rule-set:fake-ip-filter-set'
  default-nameserver:
    - system
    - 223.5.5.5 # AliDNS
    - 208.67.222.222 # OpenDNS
    - 2400:3200::1 # AliDNS
    - 2620:119:35::35 # OpenDNS
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
    - https://doh.opendns.com/dns-query
  nameserver-policy: {}
  proxy-server-nameserver: []
  direct-nameserver: []
  direct-nameserver-follow-policy: false
  fallback: []
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
    domain:
      - +.google.com
      - +.facebook.com
      - +.youtube.com
hosts: {}
