dns:
  enable: true
  ipv6: true
  listen: :53
  prefer-h3: true
  use-hosts: false
  use-system-hosts: false
  respect-rules: false
  cache-algorithm: arc
  default-nameserver:
    - 223.5.5.5 # AliDNS
    - 114.114.114.114 # 114DNS
    - 1.1.1.1 # Cloudflare DNS
    - 208.67.222.222 # Cisco OpenDNS
    - system # System
  nameserver:
    - 'https://dns.alidns.com/dns-query'
    - 'https://doh.pub/dns-query'
    - 'https://doh.360.cn/dns-query'
    - 'https://dns.cloudflare.com/dns-query'
    - 'https://doh.opendns.com/dns-query'
    - 'https://dns.google/dns-query'
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - rule-set:fake-ip-filter-set
    - MATCH,fake-ip
  fake-ip-filter-mode: blacklist
  fallback: []
  fallback-filter:
    domain:
      - +.google.com
      - +.facebook.com
      - +.youtube.com
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
