[settings]
experimental = true
lockfile = true

[dotfiles]
"/etc/sysctl.d/50-unprivileged-ports.conf/unprivileged-ports".line = "net.ipv4.ip_unprivileged_port_start = 80"
"/etc/sysctl.d/50-unprivileged-ports.conf/unprivileged-ports".variants = [{ os = "linux" }]

# System Appearance
[tools."github:Tatsu-syo/noMeiryoUI"]
os = "windows"
version = "latest"
version_prefix = "TAG-"
asset_pattern = "noMeiryoUI*.zip"

# Development Environment
# -- Environment
[tools.node]
version = "latest"

[tools.java]
version = "latest"

[tools.bun]
version = "latest"

[tools.python]
version = "3.13"

# -- CLI / TUI Tools
[tools.starship]
version = "latest"

[tools.zoxide]
version = "latest"

[tools.yazi]
version = "latest"

[tools.fd]
version = "latest"

[tools.ripgrep]
version = "latest"

[tools.lazygit]
version = "latest"

[tools.hyperfine]
version = "latest"

[tools.bottom]
version = "latest"

[tools.gdu]
version = "latest"
