[settings]
experimental = true
lockfile = true

# -- Version Control
[tools.lazygit]
version = "latest"

# -- Explorers
[tools.zoxide]
version = "latest"

[tools.ripgrep]
version = "latest"

[tools.fd]
version = "latest"

[tools.yazi]
version = "latest"

# -- IME
[tools."http:im-select"]
os = "windows"
version = "1.0.1"
url = "https://github.com/daipeihust/im-select/raw/refs/heads/master/win/out/x64/im-select.exe"

[tools."github:laishulu/macism"]
version = "3.1.1"
os = "macos"

[tools."github:laishulu/macism".platforms]
macos-arm64 = { asset_pattern = "macism-arm64" }
macos-x64 = { asset_pattern = "macism-x86_64" }

# -- Editor
[tools.tree-sitter]
version = "latest"

# -- Quality
[tools.hyperfine]
version = "latest"

[tools.hk]
version = "latest"

# -- JS / TS
[tools.bun]
version = "latest"

[tools.node]
version = "24"

[tools.aube]
version = "latest"

# -- Zig
[tools.zig]
version = "latest"

# -- Go
[tools.go]
version = "latest"

# -- Java
[tools.java]
version = "graalvm-community-25"

# -- C / C++
[tools."github:niXman/mingw-builds-binaries"]
os = "windows"
version = "16.1.0-rt_v14-rev1"
version_prefix = ""
asset_pattern = "x86_64-*-release-posix-seh-ucrt-*.7z"
