#:schema https://fnox.jdx.dev/schema.json
default_provider = "share"

[providers.share]
type = "age"
recipients = [
  "age1z6r25k45m62lh2wmf5tye0rq5w065u25xczlmxzwa8rtaktr7eeqsk9mju",
  "age194ayc2p0wgdt697an6gwxjksatjflzqee3j4nfnnf672erzksqlsxj8668"
]

[providers.work]
type = "age"
recipients = ["age1z6r25k45m62lh2wmf5tye0rq5w065u25xczlmxzwa8rtaktr7eeqsk9mju"]

[providers.work-wsl]
type = "age"
recipients = ["age194ayc2p0wgdt697an6gwxjksatjflzqee3j4nfnnf672erzksqlsxj8668"]

[secrets]

[profiles]

[profiles.work]

[profiles.work.secrets]
PI_PROVIDER_XIAOXI_API_KEY = { provider = "work", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NFZJN0l1SnJPODE5QTlYZW5nalFITWt5ZFc0OC9YZnJvM1hpWW85N25ZCmZQQVk1R3dVd1dtY1dXZFFtVGxsMW5qYkkxOXBJVXkwUU5CZkM3bENzTGsKLT4gWDI1NTE5IDkzSnROTFJGdUlWcGJNME9TLy9ZSkFIRnk3dUlOak1pN043MTZkeG5GMUkKbm5JWEF5dTFMaXVXS3dVOVRtc0ZXMll6dFBOTjNhUCtIUm9TcUZmL3UxUQotPiAiRC1ncmVhc2UgIyBRXSQzaSBdOkJKZk0KRE91MzRhOGNQYzJzRTcranBzU3M0K1hUZ2E5K2JFY3ZKSFNCcmd1ZFZtV2ZIcDlGNGNNWWJ2clNZRVU4L0cvVApRdDRRYW1Fb2VQdmRUTTJHS2FEVVRsOGYyOVZECi0tLSBEZ0lhalJ2MG1hU1ZNdmNCdzRtV2ZEMDVTWDYxMUJrSlpHQnJUcVZJV0dvCinvTmHWxksTDRG/2b312Xa8EYhrxvRlv4JxaJRvgvQ8YJtFPQl7MUQReEJyyEI1XkTwqV275L2UFw==" }
PI_PROVIDER_DEEPSEEK_API_KEY = { provider = "work", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeTJiT2swV2RFUWp5cmFQVTlDWjFQSmV5b09sVUI4VXhtbzdOUnE3SGhVCk1nVWJRVHdqdFdPblh4WTBpdEEwQlFaRkdvQ0Jza0p5NDY3S2c2bGJLOWcKLT4gWDI1NTE5IHV3MVpLWllVaFQwQ1h4TzQwZEFSOFpTR2lvSGtQenU4dXNoRFNIVXBnazgKZzRVaU1QRWRLUm4yTnd4U01BK3lXY1VKOHZ3ZUxGWUlWcE9tUTRFSEVzOAotPiBMLWdyZWFzZQpLRm5UWkh4SEEwRXd2Zit5ZGlaQzBmQTVJZzQKLS0tIGpra2Y5L3djQjBscXU2blNOaStBTjVGeW42ZDVTUWhobTdWWDl5Y0JNc28KtyKw3guQ4Fa1osWonkMdCCyrDjQ8OMuHOCbcxU9T7iGgwd3Rn392cZDK35cmZ+x37y9ENxCSqJCbWr4cAhBiebkvHQ==" }
PI_PROVIDER_OPENROUTER_API_KEY = { provider = "work", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MVFrZWp3LzBncDE1M2NiOGx4NE0xbklidWdmd3pwb3BJUmk2UW1zZ2wwCm5JbSt1UStBMzEwQThNWUxKMnkvVEovMFF3TGRxMEVzNDlmaWRLZlZicmsKLT4gMSMtZ3JlYXNlICowS0Igdlk3VzcgfVI+aE8rWgpUK1phc2dvUEJka0lKWjM0amhjNk0ycWRnZmp2UGhKRmUxY3puRWNteXk3amNSRVlBMzFoQnRVQVRjZjhJalpXCmxKM0hDREtrL28wMklRCi0tLSBWc29NbnV6RlNOMTh3SlR4Sy9jYjdiWVJXTUcrMmJxRW5vQ3g0OVdORDNrCh1RJjkU7rkIyDlffqlUQrFD/hchf6G6thhlq9Chy6WZXa/8iRgCWrBY50HorQtoGq2Itt57Wf2phDWJAjBmoC7g5nPPEfUIFu6K1BJuyjEqP3gwM84DbHIctbCE1Q7sRW8m//OQheyv0Q==" }
