#:schema https://fnox.jdx.dev/schema.json
default_provider = "age"

[providers.age]
type = "age"
recipients = [
  "age1et3h9pd7lc3r3wd0sjh7n8pc098vem5rfyal258ujznvan8ke53s64vny6", # @dev
  "age1qeanfmg7qhdrf38u77n8ntg5j05nx04frmvjcmvcf5hsqr0g9ugsxrd9ng", # @dev-wsl
  "age1z6r25k45m62lh2wmf5tye0rq5w065u25xczlmxzwa8rtaktr7eeqsk9mju", # @work
  "age194ayc2p0wgdt697an6gwxjksatjflzqee3j4nfnnf672erzksqlsxj8668" # @work-wsl
]

[secrets]
EXA_API_KEY = { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmL1NtaXZhVmthZFBqRnVoV3piRnZmM3ZCVzdXeVJNV1g3Z2hZTHJuYkhvClBueUp0ZUlPdXYxelRSUHlTeEUwR0ZEY2JUbmxJbElKT2xza3EvUXNTTVEKLT4gWDI1NTE5IGRMRXRjVzBOVnZOd0lHSWJrRkFhckc4VTZsMWR1QS80cUNjL2pvTnc1VmMKSUw3RGNuTkV1QXZDUXlkaHVtaGxsS1VXak03T0YvTWQzRjB2TlJnc2gwbwotPiBYMjU1MTkgZUZSKzRtS3pPeTE1Zmx6SUR6eTNoTEQ4RTJlQ1p5KzJIMW9TSlUzc3JWdwpKT1lHbGlPYU1EV1d6eEJJL0FBcEZwWGFPWGpVcDN6Uk5pV2dWWjc4RFFBCi0+IFgyNTUxOSBWcyt2RlhUK0R6Q1kzYVpoODBUcUIzeTlRVC9iOVNsdDVhSkxrUHJEaWdBCnppbU4vVmhTd1FFelhQV1V2eWk3QzllMGYyN00rQ2ZEak1zcCtSeDJVUjgKLT4gWVF7LWdyZWFzZQpzOThyRkxCOFZFanoxWk9ObmtJMGxvQmdYQThZckhDOW16SEFiZ0kwaGIwCi0tLSAvQWNzLy9HSU5MZGtpeXpyVWpCTTFudERaa01QNXpGM3R1MTcyQ2F3Wnk0CvHZ2uQCaCozQn8o220ui2KQ2uD7x7f3SRzI58ikQ3M3thpQvz0pShxSgtvaa45bNIjz/w3bpxUhkD2/W8lZ23qgbCX2" }
